### ISSUE TITLE
Constant crashes when using Hyberobrea

### ISSUE THREAD

**Issue by castertroyII** [kawaii/Hyperborea#11]
Since Hyberborea has been updated for DT it continues to crash on me. If I load any zone, trial, dungeon, etc from a Dawn Trail area the game will crash. If I lose up any zone pre-DT, the game crashes as well - takes longer and usually while I'm in a gpose. When in a DT area, the crash occurs without entering gpose. Logs for todays crashes attached along with screenshots of the error I see on my side.

[dalamud_appcrash_20240907_122645_699_23108.zip](https://github.com/user-attachments/files/16919720/dalamud_appcrash_20240907_122645_699_23108.zip)

![Screenshot 2024-09-07 131337](https://github.com/user-attachments/assets/5f64e274-69a9-4d2d-8cd7-a75

![Screenshot 2024-09-07 131845](https://github.com/user-attachments/assets/d6b2a6de-1191-40c3-98ae-71c4a01e11dc)
c183842eb)

**Comment by Limiana** [comment]
@castertroyII do you actually _own_ Dawntrail?
As for second one, please send your `%appdata%\XIVLauncher\pluginConfigs\Hyperborea\DefaultConfig.yaml` (and then delete it while game is off and it'll likely be fixed, just send it first so I can investigate it)

> [dalamud_appcrash_20240907_122645_699_23108.zip](https://github.com/user-attachments/files/16919720/dalamud_appcrash_20240907_122645_699_23108.zip)
It's .log file that's needed, not .dmp

**Comment by castertroyII** [comment]
Hi there. Yes, I purchased Dawntrail and have completed it. Sorry for sending the wrong file, correct .log file attached. I'll remove the yaml file as suggested. I should note there are others reporting the same issue when I asked about the crashes. I don't know if they are caught up in DT or not.

[yaml file.zip](https://github.com/user-attachments/files/16923251/yaml.file.zip)

[dalamud_appcrash_20240907_122645_699_23108.log](https://github.com/user-attachments/files/16923270/dalamud_appcrash_20240907_122645_699_23108.log)

**Comment by Limiana** [comment]
yes, your yaml file is missing opcodes. 
As for crash, can you disable all other plugins, especially related to modding, and try again without anything but hyperborea?

**Comment by castertroyII** [comment]
Turning off every other plugin (with Hyberborea being the only active one) I have 0 crashes. Roaming maps in DawnTrail or while gpose is up.

**Comment by Limiana** [comment]
> Turning off every other plugin (with Hyberborea being the only active one) I have 0 crashes. Roaming maps in DawnTrail or while gpose is up.

To find out which exactly plugin causing crashes, you can slowly turn them on one by one or in batches
